apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $IMAGE_NAME
spec:
  template:
    spec:
      serviceAccountName: $CLOUD_RUN_SERVICE_ACCOUNT
      containers:
      - image: $REGISTRY_IMAGE:$GITHUB_SHA
        env:
        - name: NODE_ENV
          value: $NODE_ENV
